config/routes.rb
Rails.application.routes.draw do
  get 'training_sessions/index'
  devise_for :users

  # Pages Controller
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :training_sessions, only: [:index, :new, :create, :edit, :update, :show] do
    resources :bookings, only: [ :new, :create]
  end
  resources :bookings, only: [:index]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer, :class_name => "User"
  belongs_to :training_session
end

app/models/training_session.rb
class TrainingSession < ApplicationRecord
  # extend TimeSplitter::Accessors
  belongs_to :trainer, :class_name => "User"
  # split_accessor :date, date_format: "%D"
  # split_accessor :start_time
  # split_accessor :end_time
  # split_accessor :start_time, :end_time, time_format: "%I:%M%p"
  validates :category, presence: true
  validates :description, presence: true
  validates :cost, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  has_one_attached :photo
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  include PgSearch::Model
  pg_search_scope :global_search,
  against: [ :category, :address ],
  associated_against: {
    trainer: [ :name ]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, :class_name => "Booking", :foreign_key => "customer_id"
  has_many :training_sessions, :class_name => "TrainingSession", :foreign_key => "trainer_id"
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :phone_number, :name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :phone_number, :name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def new
  end

  def create
    @booking = Booking.new
    @booking.training_session_id = params[:training_session_id]
    @booking.customer_id = current_user.id
      if @booking.save
          redirect_to training_session_path(@booking.training_session.id)
      else
          render "training_Session/show"
      end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard
    @bookings = current_user.bookings
    @t_sessions = current_user.training_sessions
  end

end

app/controllers/training_sessions_controller.rb
class TrainingSessionsController < ApplicationController
  before_action :set_training_session, only: [ :update, :show]

  def index
    @categories = ["Yoga", "Running", "Boxing", "Weights", "Kettle Bells", "Spinning", "Kickboxing", "Pilates"]
    if params[:query].present?
      @t_sessions = TrainingSession.global_search(params[:query])
      @markers = @t_sessions.geocoded.map do |t_session|
        {
          lat: t_session.latitude,
          lng: t_session.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { t_session: t_session })
        }
      end
        @query = params[:query]
    else
      @t_sessions = TrainingSession.all
      @markers = @t_sessions.geocoded.map do |t_session|
        {
          lat: t_session.latitude,
          lng: t_session.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { t_session: t_session })
        }
      end
    end
  end

  def new
    @t_session = TrainingSession.new
  end

  def create
   @t_session = TrainingSession.new(strong_params)
   @t_session.trainer = current_user
   if  @t_session.save!
      redirect_to training_sessions_path(@t_session.id)
    else
      render :new
    end
  end

  def edit
  end

  def show
    @t_session = TrainingSession.find(params[:id])
    @booking = Booking.new
  end

  def update
    @t_session.update(strong_params)
    redirect_to training_sessions_path(@t_session.id)
  end

  private

  def set_training_session
    @t_session = TrainingSession.find(params[:id])
  end

  def strong_params
    params.require(:training_session).permit(:category,:description, :cost, :start_time, :end_time, :address, :photo, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<% @bookings.each do |booking| %>
  <%= booking.training_session.category %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirTrainers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="dashboard-banner">
  <h1>READY SET GO</h1>
</div>

<div class="dashboard-content">

  <h2 class="dashboard-title">Your upcoming bookings</h2>
  <div class="dashboard-upcoming-bookings">
    <!-- Cards -->
    <% @bookings.each do |b| %>
      <%= link_to training_session_path(b.training_session), class: 'dashboard-card-link' do %>
        <div class="dashboard-card">

          <% if b.training_session.photo.attached?  %>
            <%= cl_image_tag b.training_session.photo.key, crop: :fill, class: "dashboard-card-img" %>
          <% else %>
            <img height="300" width="400" src="https://res.cloudinary.com/dzyd1ynmn/image/upload/v1605792731/no_img_available_skqx9j.png">
          <% end %>
          <div class="dashboard-card-infos">
            <h2><%= b.training_session.description %></h2>
            <% trainer_name = (b.training_session.trainer.name).nil? ? "No data" : b.training_session.trainer.name; %>
            <p class="light-text"> Trainer: <%= trainer_name %> </p>
             <% date = (b.training_session.start_time).nil? ? "No data" : b.training_session.start_time; %>
            <p><%= date.to_s(:rfc822).slice(0, 16) %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <hr />

  <% if @t_sessions.nil? == false %>
    <!-- User Training Session (as a coach) -->
    <h2 class="dashboard-title">Classes that you teach</h2>
    <div class="dashboard-upcoming-trainings">
      <% @t_sessions.each do |t| %>
         <%= link_to training_session_path(t), class: 'dashboard-card-link' do %>
            <div class="dashboard-card">

          <% if t.photo.attached?  %>
             <%= cl_image_tag t.photo.key, crop: :fill,  class: "dashboard-card-img" %>
          <% else %>
            <img height="300" width="400" src="https://res.cloudinary.com/dzyd1ynmn/image/upload/v1605792731/no_img_available_skqx9j.png">
          <% end %>

              <div class="dashboard-card-infos">
                <h2><%= t.description %></h2>
                <p><%= t.start_time.to_s(:rfc822).slice(0, 16) %></p>
              </div>
            </div>
        <% end %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/shared/_card.html.erb
<% @t_sessions.each do |t_session| %>


  <div style="border-bottom: 1px solid lightgrey !important;"  class="card-result">
    <% if t_session.photo.attached?  %>
      <%= cl_image_tag t_session.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <img height="300" width="400" src="https://res.cloudinary.com/dzyd1ynmn/image/upload/v1605792731/no_img_available_skqx9j.png">
      http://res.cloudinary.com/dzyd1ynmn/image/upload/c_fill,h_300,w_400/1askgpvmvupv9jbodyzmcujo6cva
    <% end %>


    <div class="product-text">
      <h2><%=t_session.start_time.strftime('%A %d %B at %I:%M%p')%></h2>
      <div class="card-product-infos d-flex justify-content-between py-2">
        <h2><%= link_to t_session.category, training_session_path(t_session.id) %></h2>
        <h2>£<%= t_session.cost %></h2>
      </div>
      <div>
        <p><%= t_session.description %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer bg-white p-2">
    <div class="row">
    <p>A Le Wagon project by Henri, Sam, Sebastien and Ben ©</p>
    </div>
  </div>

app/views/training_sessions/_form.html.erb
<div id="container">    
  <div id="row" class="d-flex justify-content-center p-3">
    <div class="my-6">
      <h1 id="index-title" class="my-5">Air Trainers</h1>
      <div class="form-container flex-column" >
        <h3>New Training Session</h3>
      <div class="row m-2 justify-content-center">
        <%= simple_form_for [@t_session] do |f| %>
            <%= f.input :category %>
            <%= f.input :photo, as: :file %>
            <%= f.input :cost %>
            <%= f.input :description %>
            <%= f.input :address %>
            <%= f.input :start_time %>
            <%= f.input :end_time%>
            
            <%= f.submit 'New Training Session', class: 'btn btn-primary' %>
        <% end %>
        </div>  
      </div> 
    </div>
  </div> 
</div>   

app/views/training_sessions/index.html.erb
<div class="index-container border-dark ">
   <div class="cards-container border-dark">
   <h2 class="section-title">Training next to you</h2>
   <%= link_to "+Add New Session", new_training_session_path, class:"px-3", id:"new-session"  %>
    <div class="all-categories">
    <div class="categories">
      <% @categories[0..3].each do |category| %>
          <% css_class = category == @query ? "btn glow-on-hover glow-on-hover--active" : "btn glow-on-hover"  %>
          <%= link_to category, training_sessions_path(:query => category), class: css_class %>
      <% end %>
    </div>
    <div class="categories">
      <% @categories[4..7].each do |category| %>
        <% css_class = category == @query ? "btn glow-on-hover glow-on-hover--active" : "btn glow-on-hover"  %>
        <%= link_to category, training_sessions_path(:query => category), class: css_class %>
    <% end %>
      </div>
    </div>
    <div class="results-container">
        <%= render "shared/card", t_session: @t_session %>
    </div>
  </div>
  <div class="map" id="stickymap">
    <div id="map"
      style="width: 100%; height: 100%;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

  </div>
</div>

app/views/training_sessions/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.bioathletic.com.au/wp-content/uploads/2018/12/active-agile-exercise-1401796-e1545140158212-1500x732.jpg);">
</div>

<%= render "form", session: @t_session %>

app/views/training_sessions/show.html.erb
<div class="main-container">
  <div class="top-header">
    <h2>Meet your <i class="highlighted"><%=@t_session.category%></i> coach</h2>
  </div>

  <div class="training-content-cart">
    <h5>Basket</h5>
    <p>Book <%=@t_session.category%> class at <%=@t_session.address%> for £<%=@t_session.cost%>?</p>
    <%= simple_form_for [@t_session, @booking] do |f| %>
    <%= f.submit 'book', class: 'btn btn-checkout' %>
    <%= link_to "View Basket", dashboard_path, class: 'btn btn-checkout' %>
    <% end %>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="top-container d-flex justify-content-between" style="background-image: url('https://source.unsplash.com/FodEsaNZs48/1600x900');">

          <div class="trainer-picture p-5">
          <div class="training-content-info">
            <div class="card-row">
            <h5><%=@t_session.description%></h5>
            <h5><%=@t_session.start_time.strftime('%A %d %B at %I:%M%p')%></h5>
            <%= cl_image_tag @t_session.photo.key, height: 200, width: 200, crop: :fill, class: "trainer-image" %>
            <p>I'm a University student at Manchester Met. I've been training with Boxing for 2 and a half years now after trying many other gyms. The Boxing gym I go to is open 24/7 which means I can go when I want whilst balancing university and part time work. Working out at the Boxing gym has helped improve my strength and athletic performance, which has enabled me to play top level rugby league. I find getting a workout in really helps to set me up for a productive day.</p>
            </div>
          </div>
          </div>
          <div class="spotify p-5">
            <iframe src="https://open.spotify.com/embed/playlist/03aLchHaqljucMRPz5L8Su" width="300" height="280" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
          </div>

      </div>
    </div>
  </div>
  <div class="middle-banner d-flex justify-content-center">
    <h1>A <strong>HEALTHY</strong> BODY IN A <strong>HEALTHY</strong> MIND</h1>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="training-content d-flex justify-content-between">
        <div class="container">
          <div class="cards">

            <div class="covid-card">
              <i class="fas fa-head-side-mask"></i>
              <p>Face Coverings Required while exercising</p>
            </div>

            <div class="covid-card">
              <i class="fas fa-people-arrows"></i>
              <p>Social distancing while exercising</p>
            </div>

            <div class="covid-card">
              <i class="fas fa-pump-soap"></i>
              <p>Hand sanitizer provided at class</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>